In [41]:
import numpy as np
import h5py 
import matplotlib.pyplot as plt
import pandas as pd
from mpl_toolkits.mplot3d import Axes3D

In [42]:
N = input('Ingrese el número de archivo deseado para el snapshot 125 de la multidark galaxy:')

Ingrese el número de archivo deseado para el snapshot 125 de la multidark galaxy:003

In [43]:
Archivo = f"/home/sebastian/Desktop/gal_125_SAG-7.128_BOX_{N}.hdf5"

In [44]:
with h5py.File(Archivo, "r") as archivo:
    for datos in archivo.keys():
        print(datos)

FeH_hot_halo
FeH_stars
ForestID
GalaxyHostID
GalaxyStaticID
Galaxy_Type
Halo
HaloID
InstantSfrBulge
InstantSfrQuies
MZ_ICstars
MZ_gas_bulge
MZ_gas_disk
MZ_hot_halo
MZ_stars_bulge
MZ_stars_disk
M_ICstars
M_gas_bulge
M_gas_disk
M_hot
M_star_bulge
M_star_disk
Magnitudes
MainHaloID
Mbh
OH_gas_disk_bulge
Rhalf_bulge
Rhalf_disk
SFR
SFR_bulge
SFR_bulge_DI
T_stars
Vx
Vy
Vz
X
Y
Z

In [45]:
with h5py.File(Archivo, "r") as archivo:
    MainID = archivo['MainHaloID'][:].ravel()
    HaloID = archivo['HaloID'][:].ravel()
    R200 = archivo['Halo/R200c'][:].ravel()*0.674
    G_type = archivo['Galaxy_Type'][:].ravel()
    r = archivo['Magnitudes/Mag_rS'][:].ravel()
    x = archivo['X'][:].ravel()*0.674
    y = archivo['Y'][:].ravel()*0.674
    z = archivo['Z'][:].ravel()*0.674
    Vx = archivo['Vx'][:].ravel()
    Vy = archivo['Vy'][:].ravel()
    Vz = archivo['Vz'][:].ravel()   
    Vmax = archivo['Halo/Vmax'][:].ravel()

In [46]:
# Crear un DataFrame de pandas con el conjunto de datos
data = pd.DataFrame({'MainHaloID':MainID, 'HaloID': HaloID, 'Galaxy_Type': G_type, 'r':r, 'X':x, 'Y':y, 'Z':z, 'Vx':Vx, 'Vy':Vy, 'Vz':Vz, 'R200c':R200})
data.to_csv(f'Simulation_{N}.csv')
# Filtrar por número de galaxias pertenecientes a cada halo
#groups_filter = data.groupby('MainHaloID').filter(lambda x: 3 < len(x) <= 10 and x['r'].max() <= -18 and (x['r'].max() - x['r'].min()) <= 3)
#groups_filter

In [47]:
# Filtrar por número de galaxias pertenecientes a cada halo
groups_filter = data.groupby('MainHaloID').filter(lambda x: 3 < len(x) <= 10 and (x['r'].max() - x['r'].min()) <= 3)
groups_filter

,MainHaloID,HaloID,Galaxy_Type,r,X,Y,Z,Vx,Vy,Vz,R200c
9425,12569369026,12569369026,0,-15.122359,28107.351562,88475.656250,148369.718750,-446.959991,-511.679993,-523.400024,35.202995
9426,12569369026,12569369026,2,-14.018427,28740.912109,87205.187500,146183.500000,-273.589752,-852.831421,-1114.021729,16.246756
9427,12569369026,12569369026,2,-13.213795,29758.958984,87879.132812,145638.500000,-8.188843,-675.859802,-1258.957031,14.795752
9428,12569369026,12569369026,2,-14.124957,28312.890625,87658.890625,148756.000000,-366.742462,-805.804199,-383.599487,22.434767
9429,12569369026,12569369026,2,-15.022037,28024.101562,87277.539062,149068.734375,-479.088623,-982.494690,-264.520569,23.376907
...,...,...,...,...,...,...,...,...,...,...,...
1515379,12705784405,12705784406,1,-17.347816,653787.687500,614198.812500,340415.625000,-1.590000,231.940002,-252.250000,40.700394
1516640,12705913618,12705913618,0,-17.768898,636027.187500,607717.625000,516091.875000,-305.660004,-210.440002,-604.169983,48.909039
1516641,12705913618,12705913618,2,-17.035645,636035.937500,607694.500000,516086.906250,-288.777161,-171.684631,-643.342041,28.273693
1516642,12705913618,12705913631,1,-17.785755,636055.187500,607680.000000,516081.812500,-262.109985,67.370003,454.619995,40.700394
1516643,12705913618,12705913631,2,-15.369218,635912.000000,607588.250000,516131.437500,-280.043640,53.643856,432.692352,21.995770

In [48]:
groups_filter['Distancia XY'] = np.sqrt(groups_filter['X']**2 + groups_filter['Y']**2)
groups_filter['Distancia YZ'] = np.sqrt(groups_filter['Y']**2 + groups_filter['Z']**2)
groups_filter['Distancia XZ'] = np.sqrt(groups_filter['X']**2 + groups_filter['Z']**2)
groups_filter['m_rx'] = groups_filter['r'] + 5*np.log10(groups_filter['Distancia XY']*1000) - 5
groups_filter['m_ry'] = groups_filter['r'] + 5*np.log10(groups_filter['Distancia YZ']*1000) - 5
groups_filter['m_rz'] = groups_filter['r'] + 5*np.log10(groups_filter['Distancia XZ']*1000) - 5
groups_filter

,MainHaloID,HaloID,Galaxy_Type,r,X,Y,Z,Vx,Vy,Vz,R200c,Distancia XY,Distancia YZ,Distancia XZ,m_rx,m_ry,m_rz
9425,12569369026,12569369026,0,-15.122359,28107.351562,88475.656250,148369.718750,-446.959991,-511.679993,-523.400024,35.202995,92833.000000,172746.968750,151008.593750,19.716152,21.064693,20.772648
9426,12569369026,12569369026,2,-14.018427,28740.912109,87205.187500,146183.500000,-273.589752,-852.831421,-1114.021729,16.246756,91819.304688,170218.562500,148982.062500,20.796244,22.136606,21.847242
9427,12569369026,12569369026,2,-13.213795,29758.958984,87879.132812,145638.500000,-8.188843,-675.859802,-1258.957031,14.795752,92781.132812,170097.953125,148647.796875,21.623505,22.939701,22.646996
9428,12569369026,12569369026,2,-14.124957,28312.890625,87658.890625,148756.000000,-366.742462,-805.804199,-383.599487,22.434767,92117.867188,172662.765625,151426.437500,20.696762,22.061035,21.776051
9429,12569369026,12569369026,2,-15.022037,28024.101562,87277.539062,149068.734375,-479.088623,-982.494690,-264.520569,23.376907,91666.343750,172739.265625,151680.046875,19.789013,21.164921,20.882603
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1515379,12705784405,12705784406,1,-17.347816,653787.687500,614198.812500,340415.625000,-1.590000,231.940002,-252.250000,40.700394,897038.750000,702227.125000,737103.187500,22.416241,21.884571,21.989822
1516640,12705913618,12705913618,0,-17.768898,636027.187500,607717.625000,516091.875000,-305.660004,-210.440002,-604.169983,48.909039,879688.187500,797290.125000,819073.500000,21.952744,21.739182,21.797714
1516641,12705913618,12705913618,2,-17.035645,636035.937500,607694.500000,516086.906250,-288.777161,-171.684631,-643.342041,28.273693,879678.500000,797269.312500,819077.125000,22.685974,22.472378,22.530975
1516642,12705913618,12705913631,1,-17.785755,636055.187500,607680.000000,516081.812500,-262.109985,67.370003,454.619995,40.700394,879682.437500,797254.937500,819088.937500,21.935879,21.722229,21.780899
1516643,12705913618,12705913631,2,-15.369218,635912.000000,607588.250000,516131.437500,-280.043640,53.643856,432.692352,21.995770,879515.500000,797217.125000,819009.000000,24.352001,24.138668,24.197227

In [49]:
groups_filter['m_mean'] = (groups_filter['m_rx'] + groups_filter['m_ry'] + groups_filter['m_rz'])/3
groups_filter

,MainHaloID,HaloID,Galaxy_Type,r,X,Y,Z,Vx,Vy,Vz,R200c,Distancia XY,Distancia YZ,Distancia XZ,m_rx,m_ry,m_rz,m_mean
9425,12569369026,12569369026,0,-15.122359,28107.351562,88475.656250,148369.718750,-446.959991,-511.679993,-523.400024,35.202995,92833.000000,172746.968750,151008.593750,19.716152,21.064693,20.772648,20.517832
9426,12569369026,12569369026,2,-14.018427,28740.912109,87205.187500,146183.500000,-273.589752,-852.831421,-1114.021729,16.246756,91819.304688,170218.562500,148982.062500,20.796244,22.136606,21.847242,21.593363
9427,12569369026,12569369026,2,-13.213795,29758.958984,87879.132812,145638.500000,-8.188843,-675.859802,-1258.957031,14.795752,92781.132812,170097.953125,148647.796875,21.623505,22.939701,22.646996,22.403402
9428,12569369026,12569369026,2,-14.124957,28312.890625,87658.890625,148756.000000,-366.742462,-805.804199,-383.599487,22.434767,92117.867188,172662.765625,151426.437500,20.696762,22.061035,21.776051,21.511282
9429,12569369026,12569369026,2,-15.022037,28024.101562,87277.539062,149068.734375,-479.088623,-982.494690,-264.520569,23.376907,91666.343750,172739.265625,151680.046875,19.789013,21.164921,20.882603,20.612179
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1515379,12705784405,12705784406,1,-17.347816,653787.687500,614198.812500,340415.625000,-1.590000,231.940002,-252.250000,40.700394,897038.750000,702227.125000,737103.187500,22.416241,21.884571,21.989822,22.096878
1516640,12705913618,12705913618,0,-17.768898,636027.187500,607717.625000,516091.875000,-305.660004,-210.440002,-604.169983,48.909039,879688.187500,797290.125000,819073.500000,21.952744,21.739182,21.797714,21.829880
1516641,12705913618,12705913618,2,-17.035645,636035.937500,607694.500000,516086.906250,-288.777161,-171.684631,-643.342041,28.273693,879678.500000,797269.312500,819077.125000,22.685974,22.472378,22.530975,22.563110
1516642,12705913618,12705913631,1,-17.785755,636055.187500,607680.000000,516081.812500,-262.109985,67.370003,454.619995,40.700394,879682.437500,797254.937500,819088.937500,21.935879,21.722229,21.780899,21.813004
1516643,12705913618,12705913631,2,-15.369218,635912.000000,607588.250000,516131.437500,-280.043640,53.643856,432.692352,21.995770,879515.500000,797217.125000,819009.000000,24.352001,24.138668,24.197227,24.229300

In [50]:
# Filtrar por magnitud aparente
groups_filter = groups_filter.groupby('MainHaloID').filter(lambda x: (14 < x['m_rx']).all() and (x['m_rx'] <= 17.77).all())
groups_filter

Empty DataFrame
Columns: [MainHaloID, HaloID, Galaxy_Type, r, X, Y, Z, Vx, Vy, Vz, R200c, Distancia XY, Distancia YZ, Distancia XZ, m_rx, m_ry, m_rz, m_mean]
Index: []

In [51]:
#Identificar la galaxia host y las galaxias satélite en cada grupo
def calcular_dispersion(group):
    galaxia_host = group[group['Galaxy_Type'] == 0]
    galaxias_satelite = group[group['Galaxy_Type'].isin([1, 2])]

    #Restar las velocidades de las galaxias satélite respecto a la galaxia host
    dispersion_velocidades = galaxias_satelite[['Vx', 'Vy', 'Vz']] - galaxia_host[['Vx', 'Vy', 'Vz']].values[0]

    #Calcular la magnitud de la dispersión de velocidades
    dispersion_magnitud = dispersion_velocidades.apply(lambda x: (x**2).sum()**0.5, axis=1)

    return dispersion_magnitud.mean()

#Aplica la función a cada grupo y obtén la dispersión de velocidades promedio
dispersion_promedio = groups_filter.groupby('MainHaloID').apply(calcular_dispersion)

print(dispersion_promedio)

Empty DataFrame
Columns: []
Index: []

In [52]:
groups_filter['Dispersion'] = groups_filter['MainHaloID'].map(dispersion_promedio)
groups_filter

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
cg = groups_filter.groupby('MainHaloID').filter(lambda x: x['Dispersion'].mean() < 1000)
cg

In [ ]:
#def scatter_plot(ax, eje1, eje2, title):
#    ax.scatter(cg.head(4)[eje1], cg.head(4)[eje2], marker= '*')
#    ax.set_title(title)

#Crear una figura y ejes para los subgráficos
#fig, axs = plt.subplots(1, 3, figsize=(16, 4))

#Crear el primer gráfico con el conjunto de datos 
#scatter_plot(axs[0], 'X', 'Y', 'Plano XY')

#Crear el segundo gráfico con el conjunto de datos 
#scatter_plot(axs[1], 'Z', 'Y', 'Plano YZ')

#Crear el tercer gráfico con el conjunto de datos 
#scatter_plot(axs[2], 'X', 'Z', 'Plano XZ')

In [ ]:
# Crear una figura con tres subgráficos en una fila
#fig, axs = plt.subplots(1, 3, figsize=(15, 5))

# Iterar sobre las filas del DataFrame
#for index, row in cg.iterrows():
    # Primer gráfico: Posición X vs. Posición Y
#    axs[0].scatter(cg['X'], cg['Y'])
#    axs[0].set_title('Posición X vs. Posición Y')
#    axs[0].set_xlabel('Posición X')
#    axs[0].set_ylabel('Posición Y')
    # Agregar el círculo centrado en la galaxia host con el radio especificado
#    if row['Galaxy_Type'] == 0:
#        circle = plt.Circle((row['X'], row['Y']), 2*row['R200c'], color='r', fill=False)
#        axs[0].add_patch(circle)

    # Segundo gráfico: Posición Y vs. Posición Z
#    axs[1].scatter(cg['Y'], cg['Z'])
#    axs[1].set_title('Posición Y vs. Posición Z')
#    axs[1].set_xlabel('Posición Y')
#    axs[1].set_ylabel('Posición Z')
    # Agregar el círculo centrado en la galaxia host con el radio especificado
#    if row['Galaxy_Type'] == 0:
#        circle = plt.Circle((row['Y'], row['Z']), 2*row['R200c'], color='r', fill=False)
#        axs[1].add_patch(circle)

    # Tercer gráfico: Posición X vs. Posición Z
#    axs[2].scatter(cg['X'], cg['Z'])
#    axs[2].set_title('Posición X vs. Posición Z')
#    axs[2].set_xlabel('Posición X')
#    axs[2].set_ylabel('Posición Z')
    # Agregar el círculo centrado en la galaxia host con el radio especificado
#    if row['Galaxy_Type'] == 0:
#        circle = plt.Circle((row['X'], row['Z']), 2*row['R200c'], color='r', fill=False)
#        axs[2].add_patch(circle)

# Ajustar el diseño de los subgráficos
#plt.tight_layout()

# Mostrar los gráficos
#plt.show()

In [ ]:
#Para seleccionar solo el R200 de la galaxia host
cg['Host_R200'] = cg.groupby('MainHaloID')['R200c'].transform('first')
cg['Host_Distancia XY'] = cg.groupby('MainHaloID')['Distancia XY'].transform('first')
cg['Host_Distancia YZ'] = cg.groupby('MainHaloID')['Distancia YZ'].transform('first')
cg['Host_Distancia XZ'] = cg.groupby('MainHaloID')['Distancia XZ'].transform('first')

# Calcula el tamaño angular para cada dirección usando el R200 de la galaxia host en su grupo
cg['Tamaño Angular del grupo XY (arcsec)'] = 2*np.arctan((2*cg['Host_R200'])/(cg['Host_Distancia XY']))*3600
cg['Tamaño Angular del grupo YZ (arcsec)'] = 2*np.arctan((2*cg['Host_R200'])/(cg['Host_Distancia YZ']))*3600
cg['Tamaño Angular del grupo XZ (arcsec)'] = 2*np.arctan((2*cg['Host_R200'])/(cg['Host_Distancia XZ']))*3600

cg.drop('Host_R200', axis=1, inplace=True)
cg.drop('Host_Distancia XY', axis=1, inplace=True)
cg.drop('Host_Distancia YZ', axis=1, inplace=True)
cg.drop('Host_Distancia XZ', axis=1, inplace=True)
cg

In [ ]:
def brillo(group):
    brillo_xy = -2.5 * np.log10((np.sum(10 ** (-0.4 * group['m_rx']))) / (np.pi * group['Tamaño Angular del grupo XY (arcsec)'] ** 2))
    brillo_yz = -2.5 * np.log10((np.sum(10 ** (-0.4 * group['m_ry']))) / (np.pi * group['Tamaño Angular del grupo YZ (arcsec)'] ** 2))
    brillo_xz = -2.5 * np.log10((np.sum(10 ** (-0.4 * group['m_rz']))) / (np.pi * group['Tamaño Angular del grupo XZ (arcsec)'] ** 2))

    # Calcular el brillo promedio y asignar el resultado a cada fila del grupo
    brillo_promedio = (brillo_xy + brillo_yz + brillo_xz) / 3
    group['Brillo Superficial'] = brillo_promedio

    return group

# Aplicar la función a cada grupo y luego combinar los resultados
cg = cg.groupby('MainHaloID').apply(brillo)
cg

In [ ]:
cg.loc[cg['Brillo Superficial'] < 26.33]

In [ ]:
candidatos_fase3 = cg.loc[cg['Galaxy_Type'] == 0]
candidatos_fase3.to_csv(f'candidatos_fase3_{N}.csv')